export const PAYROLL_TEMPLATE_VERSION = '1.0'
export const PAYROLL_COLUMN_COUNT = 87

const f = (column, key, header, label, type, group, options = {}) => ({
  column,
  key,
  header,
  label,
  type,
  group,
  designer: options.designer !== false,
  required: options.required === true,
  sensitive: options.sensitive === true,
  validateHeader: options.validateHeader !== false
})

export const COMPANY_PAYROLL_LAYOUT = [
  f(1, 'rowNo', 'No', 'No', 'INTEGER', 'SYSTEM', { designer: false }),
  f(2, 'employeeName', 'Name-Surname', 'Name-Surname', 'TEXT', 'EMPLOYEE', { required: true }),
  f(3, 'employeeCode', 'Code', 'Code', 'TEXT', 'EMPLOYEE', { required: true }),
  f(4, 'sex', 'Sex', 'Sex', 'TEXT', 'EMPLOYEE'),
  f(5, 'dateJoin', 'Date Join', 'Date Join', 'DATE', 'EMPLOYEE', { required: true }),
  f(6, 'division', 'Division', 'Division', 'TEXT', 'EMPLOYEE'),
  f(7, 'department', 'Department', 'Department', 'TEXT', 'EMPLOYEE', { required: true }),
  f(8, 'section', 'Section', 'Section', 'TEXT', 'EMPLOYEE'),
  f(9, 'position', 'Position', 'Position', 'TEXT', 'EMPLOYEE', { required: true }),
  f(10, 'payrollType', 'Type', 'Type', 'TEXT', 'EMPLOYEE'),
  f(11, 'basicWage', 'Basic Wage', 'Basic Wage', 'DECIMAL', 'EARNINGS'),
  f(12, 'seniorityAllowance', 'Seniority Allowance', 'Seniority Allowance', 'DECIMAL', 'EARNINGS'),
  f(13, 'workingDays', 'Working Days', 'Working Days', 'DECIMAL', 'WORKING'),
  f(14, 'officeDay', 'Office Day', 'Office Day', 'DECIMAL', 'WORKING'),
  f(15, 'monthEarned', 'Month Eamed', 'Month Earned', 'DECIMAL', 'WORKING'),
  f(16, 'alSlLeave', 'AL\\SL Leave', 'AL/SL Leave', 'DECIMAL', 'LEAVE'),
  f(17, 'sickLeave', 'Sick Leave', 'Sick Leave', 'DECIMAL', 'LEAVE'),
  f(18, 'paidLeave', 'Paid Leave', 'Paid Leave', 'DECIMAL', 'LEAVE'),
  f(19, 'otherLeave', '++Others', 'Other Leave', 'DECIMAL', 'LEAVE'),
  f(20, 'normalOt', 'Normal (OT)', 'Normal OT', 'DECIMAL', 'OVERTIME'),
  f(21, 'weekendOt', 'Weeked (OT)', 'Weekend OT', 'DECIMAL', 'OVERTIME'),
  f(22, 'holidayOt', 'Holiday (OT)', 'Holiday OT', 'DECIMAL', 'OVERTIME'),
  f(23, 'sick100ExtraOt', 'Sick !100% Extra TO', 'Sick 100% Extra OT', 'DECIMAL', 'OVERTIME'),
  f(24, 'otDetail1Hours', 'Hrs', 'OT Detail 1 Hours', 'DECIMAL', 'OVERTIME'),
  f(25, 'otDetail1Amount', 'Amount', 'OT Detail 1 Amount', 'DECIMAL', 'OVERTIME'),
  f(26, 'otDetail2Hours', 'Hrs', 'OT Detail 2 Hours', 'DECIMAL', 'OVERTIME'),
  f(27, 'otDetail2Amount', 'Amount', 'OT Detail 2 Amount', 'DECIMAL', 'OVERTIME'),
  f(28, 'otDetail3Hours', 'Hrs', 'OT Detail 3 Hours', 'DECIMAL', 'OVERTIME'),
  f(29, 'otDetail3Amount', 'Amount', 'OT Detail 3 Amount', 'DECIMAL', 'OVERTIME'),
  f(30, 'otDetail4Hours', 'Hrs', 'OT Detail 4 Hours', 'DECIMAL', 'OVERTIME'),
  f(31, 'otDetail4Amount', 'Amount', 'OT Detail 4 Amount', 'DECIMAL', 'OVERTIME'),
  f(32, 'pensionRiel', 'Pension (Riel)', 'Pension (Riel)', 'DECIMAL', 'DEDUCTION'),
  f(33, 'pensionUsd', 'Pension(USD)', 'Pension (USD)', 'DECIMAL', 'DEDUCTION'),
  f(34, 'transportation', 'Transportation', 'Transportation', 'DECIMAL', 'ALLOWANCE'),
  f(35, 'responseAllowance', 'Response Allowance', 'Response Allowance', 'DECIMAL', 'ALLOWANCE'),
  f(36, 'skillAllowance', 'Skill Allowance', 'Skill Allowance', 'DECIMAL', 'ALLOWANCE'),
  f(37, 'foodAllowance', 'Food Allowance', 'Food Allowance', 'DECIMAL', 'ALLOWANCE'),
  f(38, 'attendanceAllowance', 'Attendance Allowance', 'Attendance Allowance', 'DECIMAL', 'ALLOWANCE'),
  f(39, 'incentive', 'Incentive', 'Incentive', 'DECIMAL', 'ALLOWANCE'),
  f(40, 'shiftAllowance', 'Shift Allowance', 'Shift Allowance', 'DECIMAL', 'ALLOWANCE'),
  f(41, 'refund', 'Refund', 'Refund', 'DECIMAL', 'EARNINGS'),
  f(42, 'deduction', 'Deduction', 'Deduction', 'DECIMAL', 'DEDUCTION'),
  f(43, 'annualLeaveAmount', 'Amount AL', 'Amount AL', 'DECIMAL', 'DEDUCTION'),
  f(44, 'paymentedOf5Percent', 'Paymented Of %5', 'Paymented Of 5%', 'DECIMAL', 'DEDUCTION'),
  f(45, 'advance', 'Advance', 'Advance', 'DECIMAL', 'DEDUCTION'),
  f(46, 'tax', 'Tax', 'Tax', 'DECIMAL', 'DEDUCTION'),
  f(47, 'union', 'Union', 'Union', 'DECIMAL', 'DEDUCTION'),
  f(48, 'otherDeduction', 'Others', 'Other Deduction', 'DECIMAL', 'DEDUCTION'),
  f(49, 'reserved49', '', 'Reserved 49', 'TEXT', 'SYSTEM', { designer: false, validateHeader: false }),
  f(50, 'reserved50', '', 'Reserved 50', 'TEXT', 'SYSTEM', { designer: false, validateHeader: false }),
  f(51, 'grossPayBeforeDeduct', 'GrossPayBeforDeduct', 'Gross Pay Before Deduct', 'DECIMAL', 'TOTAL'),
  f(52, 'reserved52', '', 'Reserved 52', 'TEXT', 'SYSTEM', { designer: false, validateHeader: false }),
  f(53, 'actualWages', 'Actual Wages', 'Actual Wages', 'DECIMAL', 'TOTAL'),
  f(54, 'cash', 'Cash', 'Cash', 'DECIMAL', 'PAYMENT'),
  f(55, 'usd', 'USD', 'USD', 'DECIMAL', 'PAYMENT'),
  f(56, 'cent', 'Cent', 'Cent', 'DECIMAL', 'PAYMENT'),
  f(57, 'usdBankGroup', '<------------------ USD Bank ------------------>', 'USD Bank', 'TEXT', 'SYSTEM', { designer: false, validateHeader: false }),
  f(58, 'rielBankGroup', '<------------ Riel Bank ------------->', 'Riel Bank', 'TEXT', 'SYSTEM', { designer: false, validateHeader: false }),
  f(59, 'alExtra', 'Alextra', 'AL Extra', 'DECIMAL', 'LEAVE'),
  f(60, 'adjustedAlAmountExtra', 'AdjALamountextra', 'Adjusted AL Amount Extra', 'DECIMAL', 'LEAVE'),
  f(61, 'alUsePerMonth', 'AlUsePerMonth', 'AL Use Per Month', 'DECIMAL', 'LEAVE'),
  f(62, 'adjustedAlAmountMonth', 'AdjALamountMonth', 'Adjusted AL Amount Month', 'DECIMAL', 'LEAVE'),
  f(63, 'riel10000CountN', 'R10000_N', 'R10,000 Count N', 'INTEGER', 'CASH_DETAIL'),
  f(64, 'riel1000CountN', 'R1000_N', 'R1,000 Count N', 'INTEGER', 'CASH_DETAIL'),
  f(65, 'riel500CountN', 'R500_N', 'R500 Count N', 'INTEGER', 'CASH_DETAIL'),
  f(66, 'riel100CountN', 'R100_N', 'R100 Count N', 'INTEGER', 'CASH_DETAIL'),
  f(67, 'totalRielN', 'TotalRiel_N', 'Total Riel N', 'DECIMAL', 'PAYMENT'),
  f(68, 'usdN', 'USD_N', 'USD N', 'DECIMAL', 'PAYMENT'),
  f(69, 'medical', 'Medical', 'Medical', 'DECIMAL', 'BENEFIT'),
  f(70, 'benefix', 'Benefix', 'Benefix', 'DECIMAL', 'BENEFIT'),
  f(71, 'taxBenefix', 'TaxBenefix', 'Tax Benefix', 'DECIMAL', 'BENEFIT'),
  f(72, 'netBenefix', 'NetBenefix', 'Net Benefix', 'DECIMAL', 'BENEFIT'),
  f(73, 'srIdem', 'SR_IDEM', 'SR IDEM', 'DECIMAL', 'ADJUSTMENT'),
  f(74, 'srPayback', 'SR_PAYBACK', 'SR Payback', 'DECIMAL', 'ADJUSTMENT'),
  f(75, 'meal', 'Meal', 'Meal', 'DECIMAL', 'ALLOWANCE'),
  f(76, 'adjustedAmountOfAl', 'Adjamount_ofAL', 'Adjusted Amount of AL', 'DECIMAL', 'LEAVE'),
  f(77, 'accountNo', 'AccountNo', 'Account No', 'TEXT', 'PAYMENT', { sensitive: true }),
  f(78, 'usd100Count', '$100', '$100 Count', 'INTEGER', 'CASH_DETAIL'),
  f(79, 'usd50Count', '$50', '$50 Count', 'INTEGER', 'CASH_DETAIL'),
  f(80, 'usd20Count', '$20', '$20 Count', 'INTEGER', 'CASH_DETAIL'),
  f(81, 'usd10Count', '$10', '$10 Count', 'INTEGER', 'CASH_DETAIL'),
  f(82, 'usd5Count', '$5', '$5 Count', 'INTEGER', 'CASH_DETAIL'),
  f(83, 'usd1Count', '$1', '$1 Count', 'INTEGER', 'CASH_DETAIL'),
  f(84, 'cashRiel1000Count', 'R1000', 'R1,000 Count', 'INTEGER', 'CASH_DETAIL'),
  f(85, 'cashRiel500Count', 'R500', 'R500 Count', 'INTEGER', 'CASH_DETAIL'),
  f(86, 'cashRiel100Count', 'R100', 'R100 Count', 'INTEGER', 'CASH_DETAIL'),
  f(87, 'totalRiel', 'Total Riel', 'Total Riel', 'DECIMAL', 'TOTAL')
]

if (COMPANY_PAYROLL_LAYOUT.length !== PAYROLL_COLUMN_COUNT) {
  throw new Error(`Payroll layout must contain exactly ${PAYROLL_COLUMN_COUNT} fields`)
}

export const PAYROLL_FIELD_BY_KEY = new Map(COMPANY_PAYROLL_LAYOUT.map((field) => [field.key, field]))

export function getDesignerFields() {
  return COMPANY_PAYROLL_LAYOUT.filter((field) => field.designer)
}
